In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\ROHIT\Desktop\Task\linear-regression-\backend\dataset\train_dataset.csv')

In [3]:
df.head()

   feature_0    target
0   0.606175  0.117622
1   0.084838  0.068143
2   0.454541 -0.014919
3   0.091206 -0.011509
4   0.720037  0.172833

In [5]:
rows, cols=df.shape

In [8]:
random = np.zeros(10)

In [9]:
random

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
y_act = df['target']

In [129]:
def hypothesis_function(x,weight=0,bias=0):
    y_pred = weight * x + bias
    #   0 = 0 * 10 + 0
    return y_pred

In [130]:
hypothesis_function(10)

0

In [123]:
def cost_function(x,y):
    cost = (1/2*rows)*sum((hypothesis_function(x,y)-y)**2)
    return cost

In [124]:
def gradient_decent(alpha,x,y,weight, bias):
    grad_weight = (1/rows)*sum((hypothesis_function(x,y)-y)*x)
    weight = weight - alpha * grad_weight
    
    grad_bias = (1/rows)* sum(hypothesis_function(x,y)-y)
    bias = bias - alpha*grad_bias
    
    return (weight,bias)

In [151]:
def linear_regression(x,y):
    weight = .18
    bias = 0
    alpha = 0.001
    iter = 10
    for i in range(iter):
        y_pred = hypothesis_function(x,weight,bias)
        cost = cost_function(x,y)
        weight, bias = gradient_decent(alpha,x,y,weight,bias)
        
    return(weight,bias)

In [152]:
linear_regression(x,y)

(0.18015067056329753, 0.0003071156815149986)

In [142]:
#  weight = .2
#     bias = 0
#     alpha = 0.001
#     iter = 10
#(0.20015067056329755, 0.0003071156815149986)

In [43]:
df.head()

   feature_0    target
0   0.606175  0.117622
1   0.084838  0.068143
2   0.454541 -0.014919
3   0.091206 -0.011509
4   0.720037  0.172833

In [44]:
x = df['feature_0']
y = df['target']